# 生产环境
cn:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: mysql #容器名映射
    port: 13306
    database: CareerNexus
    username: root
    password: 123

  redis:
    host: 192.168.100.10
    port: 6379
    password: 123321
